# Jekyll Resume Theme

# Site settings
title: Jekyll Resume
email: hello@leyankoh.com
description: Geographer, Data Scientist, Artist
baseurl: ""
url: "https://leyankoh.github.io"
name: Kylie
job: Graduate Consultant in Intelligent Mobility
location: Manchester, UK
languages: data storytelling.
github_username: leyankoh
linkedin_username: leyankoh
email_address: hello@leyankoh.com

# Build settings
markdown: kramdown
